/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as RArticleIdRouteImport } from './routes/r.$articleId'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppFeedsRouteImport } from './routes/app/feeds'
import { Route as AppBookmarksRouteImport } from './routes/app/bookmarks'
import { Route as AppArticlesRouteImport } from './routes/app/articles'
import { Route as AppRecommendationsTodayRouteImport } from './routes/app/recommendations_.today'
import { Route as AppFeedsIdRouteImport } from './routes/app/feeds_.$id'
import { Route as AppBookmarksIdRouteImport } from './routes/app/bookmarks_.$id'
import { Route as ApiMainSplatRouteImport } from './routes/api/main.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const RArticleIdRoute = RArticleIdRouteImport.update({
  id: '/r/$articleId',
  path: '/r/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedsRoute = AppFeedsRouteImport.update({
  id: '/feeds',
  path: '/feeds',
  getParentRoute: () => AppRoute,
} as any)
const AppBookmarksRoute = AppBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AppRoute,
} as any)
const AppArticlesRoute = AppArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AppRoute,
} as any)
const AppRecommendationsTodayRoute = AppRecommendationsTodayRouteImport.update({
  id: '/recommendations_/today',
  path: '/recommendations/today',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedsIdRoute = AppFeedsIdRouteImport.update({
  id: '/feeds_/$id',
  path: '/feeds/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBookmarksIdRoute = AppBookmarksIdRouteImport.update({
  id: '/bookmarks_/$id',
  path: '/bookmarks/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiMainSplatRoute = ApiMainSplatRouteImport.update({
  id: '/api/main/$',
  path: '/api/main/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/device': typeof DeviceRoute
  '/app/articles': typeof AppArticlesRoute
  '/app/bookmarks': typeof AppBookmarksRoute
  '/app/feeds': typeof AppFeedsRoute
  '/app/settings': typeof AppSettingsRoute
  '/r/$articleId': typeof RArticleIdRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/main/$': typeof ApiMainSplatRoute
  '/app/bookmarks/$id': typeof AppBookmarksIdRoute
  '/app/feeds/$id': typeof AppFeedsIdRoute
  '/app/recommendations/today': typeof AppRecommendationsTodayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/device': typeof DeviceRoute
  '/app/articles': typeof AppArticlesRoute
  '/app/bookmarks': typeof AppBookmarksRoute
  '/app/feeds': typeof AppFeedsRoute
  '/app/settings': typeof AppSettingsRoute
  '/r/$articleId': typeof RArticleIdRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/main/$': typeof ApiMainSplatRoute
  '/app/bookmarks/$id': typeof AppBookmarksIdRoute
  '/app/feeds/$id': typeof AppFeedsIdRoute
  '/app/recommendations/today': typeof AppRecommendationsTodayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/device': typeof DeviceRoute
  '/app/articles': typeof AppArticlesRoute
  '/app/bookmarks': typeof AppBookmarksRoute
  '/app/feeds': typeof AppFeedsRoute
  '/app/settings': typeof AppSettingsRoute
  '/r/$articleId': typeof RArticleIdRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/main/$': typeof ApiMainSplatRoute
  '/app/bookmarks_/$id': typeof AppBookmarksIdRoute
  '/app/feeds_/$id': typeof AppFeedsIdRoute
  '/app/recommendations_/today': typeof AppRecommendationsTodayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/device'
    | '/app/articles'
    | '/app/bookmarks'
    | '/app/feeds'
    | '/app/settings'
    | '/r/$articleId'
    | '/app/'
    | '/api/auth/$'
    | '/api/main/$'
    | '/app/bookmarks/$id'
    | '/app/feeds/$id'
    | '/app/recommendations/today'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/device'
    | '/app/articles'
    | '/app/bookmarks'
    | '/app/feeds'
    | '/app/settings'
    | '/r/$articleId'
    | '/app'
    | '/api/auth/$'
    | '/api/main/$'
    | '/app/bookmarks/$id'
    | '/app/feeds/$id'
    | '/app/recommendations/today'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/device'
    | '/app/articles'
    | '/app/bookmarks'
    | '/app/feeds'
    | '/app/settings'
    | '/r/$articleId'
    | '/app/'
    | '/api/auth/$'
    | '/api/main/$'
    | '/app/bookmarks_/$id'
    | '/app/feeds_/$id'
    | '/app/recommendations_/today'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DeviceRoute: typeof DeviceRoute
  RArticleIdRoute: typeof RArticleIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMainSplatRoute: typeof ApiMainSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/r/$articleId': {
      id: '/r/$articleId'
      path: '/r/$articleId'
      fullPath: '/r/$articleId'
      preLoaderRoute: typeof RArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/feeds': {
      id: '/app/feeds'
      path: '/feeds'
      fullPath: '/app/feeds'
      preLoaderRoute: typeof AppFeedsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookmarks': {
      id: '/app/bookmarks'
      path: '/bookmarks'
      fullPath: '/app/bookmarks'
      preLoaderRoute: typeof AppBookmarksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/articles': {
      id: '/app/articles'
      path: '/articles'
      fullPath: '/app/articles'
      preLoaderRoute: typeof AppArticlesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recommendations_/today': {
      id: '/app/recommendations_/today'
      path: '/recommendations/today'
      fullPath: '/app/recommendations/today'
      preLoaderRoute: typeof AppRecommendationsTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/feeds_/$id': {
      id: '/app/feeds_/$id'
      path: '/feeds/$id'
      fullPath: '/app/feeds/$id'
      preLoaderRoute: typeof AppFeedsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookmarks_/$id': {
      id: '/app/bookmarks_/$id'
      path: '/bookmarks/$id'
      fullPath: '/app/bookmarks/$id'
      preLoaderRoute: typeof AppBookmarksIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/main/$': {
      id: '/api/main/$'
      path: '/api/main/$'
      fullPath: '/api/main/$'
      preLoaderRoute: typeof ApiMainSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppArticlesRoute: typeof AppArticlesRoute
  AppBookmarksRoute: typeof AppBookmarksRoute
  AppFeedsRoute: typeof AppFeedsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBookmarksIdRoute: typeof AppBookmarksIdRoute
  AppFeedsIdRoute: typeof AppFeedsIdRoute
  AppRecommendationsTodayRoute: typeof AppRecommendationsTodayRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppArticlesRoute: AppArticlesRoute,
  AppBookmarksRoute: AppBookmarksRoute,
  AppFeedsRoute: AppFeedsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppBookmarksIdRoute: AppBookmarksIdRoute,
  AppFeedsIdRoute: AppFeedsIdRoute,
  AppRecommendationsTodayRoute: AppRecommendationsTodayRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DeviceRoute: DeviceRoute,
  RArticleIdRoute: RArticleIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMainSplatRoute: ApiMainSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
